version: '3'
services:
  dashboard:
    image: mhart/alpine-node:8.9
    hostname: dashboard
    ports:
     - "9000:9000"
    volumes:
      - ./server:/server
    working_dir: /server
    command: node ./index.js
