version: '3.1'
services:
  db:
    image: postgres
    networks:
      - gorilla
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
  gorilla-server:
    image: node:8.9
    networks:
      - gorilla
    ports:
     - "9000:9000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: dev
      CONNECTION_STRING_DEV: postgres://user:password@db/db
    command: bash -c './wait-for.sh db:5432 -- node index.js'
    depends_on: 
      - db
networks:
  gorilla:
    external: false