# Create User
input CreateUserInput {
  namespace: String!
  Wname: String!
}

type CreateUserPayload {
  id: Int!
  namespace: String!
  name: String!
  groups: [Group]
  tokens: [Token]
}

# Create Group
input CreateGroupInput {
  namespace: String!
  name: String!
}

type CreateGroupPayload {
  id: Int!
  namespace: String!
  name: String!
  groups: [Group]
  tokens: [Token]
}

# Login Into Mqtt Payload
input LoginIntoMqttInput {
  namespace: String
  username: String
  password: String
  client_id: String
}

type LoginIntoMqttPayload {
  result: String!
  modifiers: Modifier
}

type Modifier {
  client_id: String
  mountpoint: String
}

# Login
input LoginInput {
  namespace: String!
  name: String!
  password: String!
}

# Subscribe
input SubscribeAuthInput {
  username: String!
  namespace: String!
  topics: [String]!
}

type SubscribeAuthPayload {
  result: String!
  namespace: String!
  modifiers: Modifier
  topics: [String]!
}

# Publish
input PublishAuthInput {
  username: String!
  namespace: String!
  topic: String!
  qos: Int!
}

type PublishAuthPayload {
  result: String!
}
